#!/usr/bin/env python3
"""Opt-in T1→T2→T3→T4 smoke against one existing Codespace."""

from __future__ import annotations

import argparse
import json
import tempfile
import uuid
from pathlib import Path

from cospaces.domain.run import RunRequest
from cospaces.services.checkpoint_service import CheckpointSaveRequest, CheckpointService
from cospaces.services.run_service import RunService
from cospaces.services.verification_service import VerificationRequest, VerificationService
from cospaces.services.workspace_lifecycle import WorkspaceLifecycleService

SCHEMA = "cospaces.live-smoke/v1"


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--codespace", required=True)
    result.add_argument("--checkpoint-root", default=".")
    result.add_argument("--stop-after", action="store_true")
    result.add_argument("--keep-checkpoint", action="store_true")
    result.add_argument("--json", action="store_true", dest="json_output")
    return result


def failure_payload(failure) -> dict[str, object]:
    return {
        "code": failure.code,
        "message": failure.message,
        "retryable": failure.retryable,
        "exit_status": int(failure.exit_status),
    }


def main() -> int:
    args = parser().parse_args()
    task_id = f"live-smoke-{uuid.uuid4().hex[:12]}"
    steps: list[dict[str, object]] = []

    workspace_service = WorkspaceLifecycleService()
    described = workspace_service.describe(args.codespace)
    if not described.ok:
        assert described.failure is not None
        return emit(args, task_id, steps, described.failure)
    assert described.workspace is not None
    target = described.workspace
    steps.append({"step": "workspace.describe", "ok": True, "workspace": target.to_dict()})

    run = RunService().execute(
        RunRequest(
            argv=("git", "status", "--short"),
            codespace=args.codespace,
            task_id=task_id,
            correlation_id="live-smoke",
            timeout_seconds=120.0,
        )
    )
    steps.append({"step": "run", "ok": run.ok, "run_id": run.record.run_id})
    if not run.ok:
        assert run.failure is not None
        return emit(args, task_id, steps, run.failure)

    with tempfile.TemporaryDirectory(prefix="cospaces-live-smoke-") as temp:
        verify_root = Path(temp)
        (verify_root / ".cospaces.toml").write_text(
            "[verify.live-smoke]\n"
            "[[verify.live-smoke.checks]]\n"
            'name = "status"\ncommand = ["git", "status", "--short"]\n'
            "timeout_seconds = 120\nrequired = true\n",
            encoding="utf-8",
        )
        verified = VerificationService(verify_root).verify(
            VerificationRequest(
                plan="live-smoke",
                codespace=args.codespace,
                task_id=task_id,
                correlation_id="live-smoke",
            )
        )
    verification_id = verified.record.verification_id if verified.record is not None else None
    steps.append({"step": "verify", "ok": verified.ok, "verification_id": verification_id})
    if not verified.ok:
        assert verified.failure is not None
        return emit(args, task_id, steps, verified.failure)

    checkpoint_root = Path(args.checkpoint_root).resolve()
    checkpoint_service = CheckpointService(checkpoint_root)
    saved = checkpoint_service.save(
        CheckpointSaveRequest(
            task_id=task_id,
            repository=target.repository,
            ref=target.ref,
            codespace=args.codespace,
            capture_git=False,
            current="live MVP smoke completed",
            next_step="manual continuation only",
            last_run_id=run.record.run_id,
            last_verification_id=verification_id,
            notes="generated by explicit live_codespace_smoke.py invocation",
        )
    )
    steps.append({"step": "checkpoint.save", "ok": saved.ok})
    if not saved.ok:
        assert saved.failure is not None
        return emit(args, task_id, steps, saved.failure)

    shown = checkpoint_service.show(task_id)
    steps.append({"step": "checkpoint.show", "ok": shown.ok})
    if not shown.ok:
        if not args.keep_checkpoint:
            cleanup_checkpoint(checkpoint_root, task_id)
        assert shown.failure is not None
        return emit(args, task_id, steps, shown.failure)

    validated = checkpoint_service.validate(task_id)
    steps.append({"step": "checkpoint.validate", "ok": validated.ok})
    if not validated.ok:
        if not args.keep_checkpoint:
            cleanup_checkpoint(checkpoint_root, task_id)
        assert validated.failure is not None
        return emit(args, task_id, steps, validated.failure)

    if not args.keep_checkpoint:
        cleanup_checkpoint(checkpoint_root, task_id)

    if args.stop_after:
        stopped = workspace_service.stop(args.codespace)
        steps.append({"step": "workspace.stop", "ok": stopped.ok})
        if not stopped.ok:
            assert stopped.failure is not None
            return emit(args, task_id, steps, stopped.failure)

    return emit(args, task_id, steps, None)


def cleanup_checkpoint(root: Path, task_id: str) -> None:
    current = root / ".cospaces" / "checkpoints" / f"{task_id}.json"
    history = root / ".cospaces" / "checkpoints" / ".history" / f"{task_id}.json"
    current.unlink(missing_ok=True)
    history.unlink(missing_ok=True)


def emit(args, task_id: str, steps: list[dict[str, object]], failure) -> int:
    payload = {
        "schema": SCHEMA,
        "ok": failure is None,
        "live_codespace": True,
        "codespace": args.codespace,
        "task_id": task_id,
        "created_workspace": False,
        "deleted_workspace": False,
        "rebuilt_workspace": False,
        "stop_after_requested": bool(args.stop_after),
        "steps": steps,
        "error": failure_payload(failure) if failure is not None else None,
    }
    print(json.dumps(payload, sort_keys=True, separators=(",", ":")))
    return 0 if failure is None else int(failure.exit_status)


if __name__ == "__main__":
    raise SystemExit(main())
